name: Build ASP.Net Core app - mudhammataan-app (Dev)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore BkashBackend.csproj

      - name: Build project
        run: dotnet build BkashBackend.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish BkashBackend.csproj -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

# Deploy step removed for Dev branch
# Deploy will happen only from Stage branch
