name: Build & Deploy (self-contained) - mudhammataan-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore
        run: dotnet restore BkashBackend.csproj

      - name: Build
        run: dotnet build BkashBackend.csproj -c Release --no-restore

      - name: Publish (self-contained win-x86)
        run: dotnet publish BkashBackend.csproj -c Release -r win-x86 --self-contained true /p:PublishSingleFile=false -o ./publish

      - name: Create correct web.config (run exe directly)
        shell: pwsh
        run: |
          $wc = Join-Path $PWD 'publish\web.config'
          $content = @'<?xml version="1.0" encoding="utf-8"?><configuration><system.webServer><handlers><add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" /></handlers><aspNetCore processPath="BkashBackend.exe" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout" hostingModel="inprocess" /></system.webServer></configuration>'@$content | Set-Content -Path $wc -Encoding UTF8

      - name: Zip published files
        run: Compress-Archive -Path publish\* -DestinationPath app.zip -Force

      - name: Deploy to Azure Web App (zip)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mudhammataan-app'
          package: 'app.zip'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_70E3E623081F48B4A1E6E8CB40CD404E }}
