name: Stage Backend Build

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set AZURE_STORAGE_KEY environment variable
        run: echo "AZURE_STORAGE_KEY=${{ secrets.AZURE_STORAGE_KEY }}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore BkashBackend.csproj

      - name: Build project
        run: dotnet build BkashBackend.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish BkashBackend.csproj -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish
