name: Stage Backend Deployment

on:
  push:
    branches:
      - stage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore BkashBackend.csproj

      - name: Build
        run: dotnet build BkashBackend.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish BkashBackend.csproj -c Release -o ./publish --no-build

      - name: Deploy to Azure Web App (Stage)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mudhammataan-app'
          slot-name: 'Staging'
          package: ./publish/*
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
